CREATE TABLE IF NOT EXISTS PUBLICATIONS (
    DOI TINYTEXT PRIMARY KEY,
    TITLE TEXT,
    AUTHORS TINYTEXT,
    JOURNAL TEXT,
    "YEAR" VARCHAR(32),
    PUBLISHED VARCHAR(255),
    EPUBLISHED VARCHAR(255),
    VOLUME VARCHAR(255),
    ISSUE TEXT,
    PAGES VARCHAR(32),
    PMID VARCHAR(255),
    LABELS TINYTEXT,
    QUALIFIERS VARCHAR(255),
    IUID VARCHAR(255),
    URL VARCHAR(255),
    DOIURL VARCHAR(255),
    PUBMEDURL VARCHAR(255)
);